@baseUrl = https://57vkrpe7w8.execute-api.us-east-1.amazonaws.com/dev/notes

###
POST {{baseUrl}}
Content-Type: application/json

{
  "id": "100",
  "title": "My first notes",
  "body": "Body for the notes"
}

{}

###
DELETE {{baseUrl}}/12
Content-Type: application/json

###
GET {{baseUrl}}
Content-Type: application/json

###
PUT {{baseUrl}}/12
Content-Type: application/json

{}

###
POST {{baseUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query GetAlarmHeader($eventId: String!) {
  getAlarmHeader(eventId: $eventId) {
    componentPath
    timestamp
    componentName
    eventStatus
    eventType
    queue
    unitName
    affectedComponents
    eventDescription
    eventId
    lastModified
    lastUserActivity
    projectId
    projectName
  }
}

{
  "eventId": "2"
}

###
POST {{baseUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query GetQueueTypes {
  getQueueTypes {
    queue
  }
}

###
POST {{baseUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query GetComponents($projectId: Float!) {
  getComponents(projectId: $projectId) {
    serialNumber
    componentTreePath
    componentType
    model
    status
    unitId
    projectId
  }
}

{
  "projectId": 132465
}

###
POST {{baseUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query GetAlarms {
  getAlarms {
    componentPath
    timestamp
    componentName
    eventStatus
    eventType
    queue
    unitName
    affectedComponents
    eventDescription
    eventId
    lastModified
    lastUserActivity
    projectId
    projectName
  }
}

###
POST {{baseUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query getProjects {
  getProjects {
    projectId
    projectName
    alarmsCount
    unitsCount
    onlineUnits
    projectType
    pointOfContact
    contactNumber
    emailId
    street1
    street2
    country
    city
    state
    zip
    customerName
    status
    lastConnection
    projectDescription
  }
}

###
POST {{baseUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query GetEvents($projectId: Float!) {
  getEvents(projectId: $projectId) {
    componentPath
    timestamp
    componentName
    eventStatus
    eventType
    queue
    unitName
    eventId
  }
}

{
  "projectId": 132465
}